import Navbar from "@/components/Navbar";
import "./globals.css";

// components
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className='box-border lg:container lg:mx-auto min-w-[800px] max-w-[1200px] h-screen'>
          <Providers>
            <div className='flex flex-col h-full space-y-5'>
              <Navbar />
              <div className='h-full'>{children}</div>
            </div>
          </Providers>
        </main>
      </body>
    </html>
  );
}
