import "./global.css";

import { Open_Sans } from "next/font/google";

// components
import Navbar from "@/components/Navbar/Navbar";
import ProviderWrapper from "@/components/ProviderWrapper";

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={open_sans.className}>
        <Navbar />
        <div className='lg:container mx-auto p-12'>
          <ProviderWrapper>{children}</ProviderWrapper>
        </div>
      </body>
    </html>
  );
}
